import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image'
import logo from '../public/ahlens-logo.png'

const Header = () => {
  return (
    <nav>
      <Head>
        <title>Nikitas Åhléns</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/ahlens.jpg' />
      </Head>
      <a>hamburger</a>
      <Link href='/favorites'>
        <a>favorites</a>
      </Link>
      <div className='logo'>
        <Link href='/'>
          <a><Image src={logo} alt="ahlens logo" width={65} height={15}/></a>
        </Link>
      </div>
      <a>Mina sidor</a>
      <a>mini basket</a>
    </nav>
  );
};

export default Header;
