import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import logo from '../public/ahlens-logo.png';
import hearticon from '../public/heart_icon.png';
import hamburgericon from '../public/hamburger_menu.png';
import personicon from '../public/person_icon.png';
import shoppingbagicon from '../public/shopping_bag_icon.png';

const Navbar = () => {
  return (
    <div>
      <Head>
        <title>Nikitas Åhléns</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/ahlens.jpg' />
      </Head>
      <nav className='navbar'>
        <button className='hamburger-icon'>
          <Image src={hamburgericon} alt='Menu icon' width={11} height={11} />
        </button>
        <div className='favorites-icon'>
          <Link href='/favorites'>
            <a>
              <Image src={hearticon} alt='Favorites icon' width={11} height={11} />
            </a>
          </Link>
        </div>
        <div className='logo'>
          <Link href='/'>
            <a>
              <Image src={logo} alt='Åhléns logo' width={65} height={15} />
            </a>
          </Link>
        </div>
        <button className='person-icon'>
          <Image src={personicon} alt='My pages icon' width={11} height={11} />
        </button>
        <button>
        <Image className="minibasket" src={shoppingbagicon} alt='Shopping bag icon' width={11} height={11} />
        </button>
      </nav>
    </div>
  );
};

export default Navbar;
